//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.29 at 12:17:36 AM CST 
//


package org.adligo.fabricate.xml.io.project.v1_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.adligo.fabricate.xml.io.library.v1_0.DependenciesType;


/**
 * <p>Java class for fabricate_project_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="fabricate_project_type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="stages" type="{http://www.adligo.org/fabricate/xml/io/project/v1_0}project_stages_type"/&gt;
 *         &lt;element name="dependencies" type="{http://www.adligo.org/fabricate/xml/io/library/v1_0}dependencies_type" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "fabricate_project_type", propOrder = {
    "stages",
    "dependencies"
})
public class FabricateProjectType {

    @XmlElement(required = true)
    protected ProjectStagesType stages;
    protected DependenciesType dependencies;

    /**
     * Gets the value of the stages property.
     * 
     * @return
     *     possible object is
     *     {@link ProjectStagesType }
     *     
     */
    public ProjectStagesType getStages() {
        return stages;
    }

    /**
     * Sets the value of the stages property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProjectStagesType }
     *     
     */
    public void setStages(ProjectStagesType value) {
        this.stages = value;
    }

    /**
     * Gets the value of the dependencies property.
     * 
     * @return
     *     possible object is
     *     {@link DependenciesType }
     *     
     */
    public DependenciesType getDependencies() {
        return dependencies;
    }

    /**
     * Sets the value of the dependencies property.
     * 
     * @param value
     *     allowed object is
     *     {@link DependenciesType }
     *     
     */
    public void setDependencies(DependenciesType value) {
        this.dependencies = value;
    }

}
