package org.adligo.fabricate.common;

/**
 * I_ProjectTask is a interface to allow plug-able tasks
 * for fabricates stages.  It is generally assumed
 * that these will occur concurrently.
 * 
 * @author scott
 *
 */
public interface I_ProjectTask {
  public void execute(String projectName);
  /**
   * This may return null if no artifacts are
   * generated by this task.
   * @return
   */
  public String getArtifactType();
}
