//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.27 at 02:12:24 PM CDT 
//


package org.adligo.fabricate.xml.io.project;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.adligo.fabricate.xml.io.project package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _FabricatProject_QNAME = new QName("http://www.adligo.org/fabricate/xml/io/project", "fabricat_project");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.adligo.fabricate.xml.io.project
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FabricateProjectType }
     * 
     */
    public FabricateProjectType createFabricateProjectType() {
        return new FabricateProjectType();
    }

    /**
     * Create an instance of {@link StagesType }
     * 
     */
    public StagesType createStagesType() {
        return new StagesType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FabricateProjectType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.adligo.org/fabricate/xml/io/project", name = "fabricat_project")
    public JAXBElement<FabricateProjectType> createFabricatProject(FabricateProjectType value) {
        return new JAXBElement<FabricateProjectType>(_FabricatProject_QNAME, FabricateProjectType.class, null, value);
    }

}
