//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.12 at 07:06:53 PM CDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.adligo.org/fabricate/xml/io_v1/dev_v1_0.xsd")
package org.adligo.fabricate.xml.io_v1.dev_v1_0;
