//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.15 at 05:35:22 PM CST 
//


package org.adligo.fabricate.xml.io_v1.fabricate_v1_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * Project groups are projects with fabricate.xml files, 
 * fabricate will be able to delegate to other fabrications.
 * 
 * <p>Java class for project_group_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="project_group_type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="scm" type="{http://www.adligo.org/fabricate/xml/io_v1/fabricate_v1_0.xsd}scm_type"/&gt;
 *         &lt;element name="project" type="{http://www.adligo.org/fabricate/xml/io_v1/fabricate_v1_0.xsd}project_type"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "project_group_type", propOrder = {
    "scm",
    "project"
})
public class ProjectGroupType {

    @XmlElement(required = true)
    protected ScmType scm;
    @XmlElement(required = true)
    protected ProjectType project;

    /**
     * Gets the value of the scm property.
     * 
     * @return
     *     possible object is
     *     {@link ScmType }
     *     
     */
    public ScmType getScm() {
        return scm;
    }

    /**
     * Sets the value of the scm property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScmType }
     *     
     */
    public void setScm(ScmType value) {
        this.scm = value;
    }

    /**
     * Gets the value of the project property.
     * 
     * @return
     *     possible object is
     *     {@link ProjectType }
     *     
     */
    public ProjectType getProject() {
        return project;
    }

    /**
     * Sets the value of the project property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProjectType }
     *     
     */
    public void setProject(ProjectType value) {
        this.project = value;
    }

}
