//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.27 at 02:12:24 PM CDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.adligo.org/fabricate/xml/io/dev")
package org.adligo.fabricate.xml.io.dev;
